"""empty message

Revision ID: cfd2519ec96e
Revises: 
Create Date: 2022-05-13 20:32:50.850367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfd2519ec96e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_to_redirect',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shortner', sa.String(), nullable=True),
    sa.Column('destination', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('url_to_redirect')
    # ### end Alembic commands ###
